language: go
sudo: required
dist: trusty
env:
  global:
  - USER=dorrybamboo REPO=rpi-x86-ex
  - secure: QopRfo6yQ4cLmK121tod/gl+tufn5VUG5SDncaO6kG5q7bD60JxfyBmkFyd49L4H/bf8kLWEV/XG4coiX7OdNWEAmVnwfIJUtNewkYOvXIvEa3mvMeVnYqzbR4cJ9dh5u0eLGDmZYr5+mYm1hn63sWMCzsZGxoCEW60Wch7HINlOLGo2hvTMnfPXD96puWtdxuT/uvTw0abzsaND0iFvJuyuq5jISB0+Ul/o8mgNous18ASM9A6Ob2FHRDbAUdSvXGWmOCbYDZPZLqfkoS2lCmypfEboWBqYNKfpG/DVl0SGu6eZkll1MaCUFqenTp9OW2Ca/twQhDTPQ7qpfAft+i+Uncn9QLoaHPxnLBpbvCW3MeVSxlUWHHG5MXty5yw5/oFgHWqPbE08J3Zt4IK90Afz6/OPbnt2IXnVzC90kt0sr/2s8EumKPIJmWR8hN/nBYfJ5I5OMoA65dYESY+b1gKPNMPbHIE9AV8Ytm7cgNdeYI/UJD7yD5B9cuIxYEDkI2MCVleE2gMKQIKAVnQqGDIL/Cl9Kb+KTdHhlZ6jV9IG0QMUZ6ecYS05pxlYwuJ3mT+8Caq6ba2x2hEypdrVA52uc4/nIu4QpAd7HK3zzjyaB2BJQ05GhHP6lEQbITHSbPR+F6Oq+BJ2GW93qmzdOffsiLcjtv5qJG88nHVg/bA=
  - secure: bjwv0kgjL69KjV5FrFWsGnoc4PYiZhY1TBKToIFiW5KCD+h4SjgEOrKcywhLKvKU0l5F2hsG8k5ovS5TADFFhHPv1lu15Djlp4rV6rrOvdA1krtZRZRfxdiJ3WIDEASlgQl4aY8reA2voQHQYOFykQOa28fVg+OKadKK6PU5QUInWzXUJCVgi/x6svdQXzwMU1QYME7rRRxXcnaUOeiglmHmCyb06OIOIEIefpYE8vDe/ej2vJQEQQvl+nxcNtkuw5VAiSdc/fyB/f3kbPXEex7+YOcQ/dqqU1cCOMe5HEKjfXbGtEHctq0QItRTN+YOFzkZEOt0oGAZ1DvYpRRFg2OGt6w5u99jE9JSH+dKjVKKi+PvLjlvpAyoWLDmz3PjOF33/pjPw9nrV5fRMw7IurqisYLI/AhO+7/IorBg2f4H8vXU7w86JjllhWUT1oidLhJrh8ze2wcjZi3kD9h6G6Uvy57aaPQbAA1xAn9V8OW5BkCrD69lHlHxvZInvLw6RaXEDgu2olktQ4BEdBRB4G68DJMKirUMlv2xOPXCfYveUPCftmt0IcO8/YrTSB+NkuHzSgJ7Z8+Ow6/Qamaetakfw4/FT9qv8tzwla0Q3OZ94m13ttPh2K94FxIzQq6JNh0bfQxiz+18zfN36+F7kHGe0GngMsU5/cSZ9oB00fM=
services:
- docker
before_script:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support
- sudo update-binfmts --enable qemu-arm
- sudo update-binfmts --display qemu-arm
- sudo sh -c "echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:'
  > /proc/sys/fs/binfmt_misc/register"
install: true
script:
- "./build"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_USER"; echo "$DOCKER_PASS";
  echo "$USER/$REPO"; docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"; docker push
  $USER/$REPO; fi
