language: go
sudo: required
dist: trusty
branches:
    only:
        - master
env:
  global:
  - USER=dorryjuice REPO=rpi-x86-ex
  - secure: oEcGzLTmRmUkBljLj1/5n4AoSCgGhVp05IrMn9oEVOD1e+nb4+PnznzcBPG0Ve9WZWGkJqEzWEbQLvfA9q5u2LHQpK5u4Emnp9T7R0CWjkMyR9LZHnHs46psV8OGdcPPc6yWWfGOwaeFn4FlwGzQBvvRGXwdDkveWze9whRD3b9OWFAwKL0Bw4TMJiZktBJtUtZsyy1X3nIcerwiHezEKRxUfRlwSLj3uKJmxtzL34n4TRGs0MZIocNgAx0yt8veBngIKvt4McfqAonM2Byg/AdK+b9xeooZrsLmP+C5iPS7ddXeRpfWdQ+z0m6f4iSKnjAVyXH53tsbRgJyDmEUL81aL2pq0g05QVWDLufniPcfYsumD4ixpXkGIvP+w49AzmfxWs6pZt0VCB/Oqt1Pt3P1lupr2zpGjC/vvr061TvNarhs4ENQpWWPuxVtGmd4HFvzNV353kcDzkwYr7g8JSyU0Ya26KlcUrjcSF+8u5DC0UjjZqwSlPkssYcFGGO+KUhuWJFBRBT1svAktQFYGJmKX8BhKBHGi1S1Q1NAQ1cmav0xMczHRmnh52gjYYI6HmrvlV1JKHHoxg1ORyBBGKrb9aruuXRh33gIeyY0VDPHL33DLrbikcyUCiaV7UTMJ7IXqTYBZYWXzE42Nc/poLpqFSg1/GNU4F64xSsRkOQ=
  - secure: DLYymlt2RR2VJJUHOdk4Et4Ugw7jjTi4dTqZqJVSNZVewUoGf6aQyujtA1v9eqaQd+mClhXQgiXGZBBgRNuB8dDzIj+9FO1LI+vA6APrbaghzAS6wFPOA3JAl5cej43amzcqpImAJT5FdofBtNkXlxhNZdwK2Mk4Z8S42FeW+mGtidtYi+wzWZJvkxh0olNI7EekyvRin7SUPMBs7/Vb2R2kUySE5E78uorjBAaeaBu8PvpnIeljTNLxAuU0uB5yH0FcnQ9gnY+hncY9PdLlXFWh0jLR5MMyYUgZNfpPiZzoRhF9h4nCgEdQ6qKtq/7M3jQBMAzhr7EKqMitviH8fFguMT7x/J7kQALXIlUXr658x3WYBouxWJq/lNFIu8uDe365KjbDWAgyAwgmmjHXqRbrQUDuYGepOokBtBVq5tcx1jPpHTKwtwyeyyckSw09jznCVpW+iI7r0yKbjgEVxOlq7brRKbH4cJxZ8KpEWWG1ceS63nKLoh8teAVxwXOsFZR9gCZ6Iu5gVOtYCe6cNLfcy6duO8kCEz/5nmvQGyUmV5sok3YhL2jlw6z9SfCbOePyq9ZrbWmldwqweG/LUSHWp2qFsiYz2YsyuSroj/XmsEw977S2I0JCHHvq0hCE72oY4Wvg3QqfL+KCsVU1VY/mfYERRiw8/PfiRdJjKk8=
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support
- sudo update-binfmts --enable qemu-arm
- sudo update-binfmts --display qemu-arm
- sudo sh -c "echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:'
  > /proc/sys/fs/binfmt_misc/register"
install: true
script:
- "./build"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_USER"; echo "$DOCKER_PASS";
  echo "$USER/$REPO"; docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"; docker push
  $USER/$REPO; fi
